config/routes.rb
PAL::Application.routes.draw do
  resources :newsletters do
    member do
      get :view
    end
    
    resources :newsletter_sections do
      collection do
        get :reorder
        post :sort
      end
    end
  end

  resources :subscribers do
    member do
      get :verify
    end
  end
  
  resources :class_requests
  resources :contacts
  resources :roles

  get "home/index"
  get "home/template"

  match 'logout' => 'user_sessions#destroy'
  
  resources :user_sessions
  resources :users
  resources :locations
  resources :meetings
  resources :certification_levels
  

  resources :certifications do
    resources :sections
  end

  resources :albums do
    resources :photos
  end

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy

  validates_presence_of :title
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  has_many :class_requests
  has_many :sections
  belongs_to :certification_level

  # scope include(:sections).order(:start_date).first  

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :certification_level_id
end

app/models/class_request.rb
class ClassRequest < ActiveRecord::Base
  belongs_to :certification
  
  validates_presence_of :from
  validates_presence_of :time
  
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :to
  validates_presence_of :from
  validates_presence_of :subject
  validates_presence_of :body
  
  validates_format_of :to, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :meetings

  validates_presence_of :name, :lat, :lng
  validates_numericality_of :lat, :lng
  validates_uniqueness_of :name
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :section
  belongs_to :location

  validates_presence_of :time
  validates_presence_of :section_id
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :newsletter_sections, :order => :position
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image #, :styles => {:display => "800x600>", :thumb => "100x100>", :tiny => "30x30>"}

  validates_presence_of :title
  validates_attachment_presence :image
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  validates_presence_of :name
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :certification
  has_many :meetings
end

app/models/subscriber.rb
require 'digest/sha2'

class Subscriber < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_uniqueness_of :email
  
  after_create :set_code
  
  def set_code
    self.code = Digest::SHA256.hexdigest("subscriber#{self.id}#{self.email}")
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments

  acts_as_authentic

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end  

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.xml
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.xml
  def show
    @meeting = Meeting.find(params[:id])
    @section = @meeting.section
    @location = @meeting.location

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.xml
  def new
    @section = Section.find( params[:section_id] )
    @meeting = @section.meetings.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.xml
  def create
    @meeting = Meeting.new(params[:meeting])

    # if a new location was submitted
    if params[:location] and !params[:location][:name].blank?
      @location = Location.new(params[:location])
      @location.save
      @meeting.location = @location
    end
    
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to(@meeting, :notice => 'Meeting was successfully created.') }
        format.xml  { render :xml => @meeting, :status => :created, :location => @meeting }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.xml
  def update
    @meeting = Meeting.find(params[:id])

    if params[:location] and !params[:location][:name].blank?
      @location = Location.new params[:location]
      @location.save
      @meeting.location = @location
    end

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to(@meeting, :notice => 'Meeting was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.xml
  def destroy
    @meeting = Meeting.find(params[:id])
    section = @meeting.section
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to([section.certification,section]) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
	      <% @meeting.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

	<%= f.hidden_field :section_id %>

  <div class="field">
    <%= f.label :location, "Choose a location: " %>
    <select name="meeting[location_id]" id="meeting_location">
        <option value=""></option>
        <option value="new">Create a new Location</option>
        <%= options_for_select Location.all.map {|loc| [loc.name, loc.id]}, :selected => @meeting.location ? @meeting.location.id : "" %>
    </select>
  </div>

  <div id="create_location">
    <div class="field">
        <label for="meeting_location_name">Location name:</label>
        <input type="text" name="location[name]" id="location_name"/>
        <input type="hidden" name="location[lat]" id="location_lat"/>
        <input type="hidden" name="location[lng]" id="location_lng"/>
    </div>
    <div id="map_for_editing"></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', [@meeting.section.certification,@meeting.section] %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Time</th>
    <th>Description</th>
    <th>Section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.time %></td>
    <td><%= meeting.description %></td>
    <td><%= meeting.section %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<h1><%= @section.certification.name %> Meeting</h1>

<p><%= @meeting.description %></p>

<p>
  <b>Time:</b>
  <%= @meeting.time %>
</p>

<% if @location %>
    <%= hidden_field_tag 'lat', @location.lat %>
    <%= hidden_field_tag 'lng', @location.lng %>

    <div id="map_for_showing"></div>
    <div id="directions_panel"></div>
<% end %>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', certification_section_path(@section.certification,@section) %>