config/routes.rb
PAL::Application.routes.draw do
  resources :newsletters do
    member do
      get :view
    end
    
    resources :newsletter_sections do
      collection do
        get :reorder
        post :sort
      end
    end
  end

  resources :subscribers do
    member do
      get :verify
    end
  end
  
  resources :class_requests
  resources :contacts
  resources :roles

  get "home/index"
  get "home/template"

  match 'logout' => 'user_sessions#destroy'
  
  resources :user_sessions
  resources :users
  resources :locations
  resources :meetings
  resources :certification_levels
  

  resources :certifications do
    resources :sections
  end

  resources :albums do
    resources :photos
  end

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy

  validates_presence_of :title
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  has_many :class_requests
  has_many :sections
  belongs_to :certification_level

  # scope include(:sections).order(:start_date).first  

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :certification_level_id
end

app/models/class_request.rb
class ClassRequest < ActiveRecord::Base
  belongs_to :certification
  
  validates_presence_of :from
  validates_presence_of :time
  
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :to
  validates_presence_of :from
  validates_presence_of :subject
  validates_presence_of :body
  
  validates_format_of :to, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :meetings

  validates_presence_of :name, :lat, :lng
  validates_numericality_of :lat, :lng
  validates_uniqueness_of :name
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :section
  belongs_to :location

  validates_presence_of :time
  validates_presence_of :section_id
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :newsletter_sections, :order => :position
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image #, :styles => {:display => "800x600>", :thumb => "100x100>", :tiny => "30x30>"}

  validates_presence_of :title
  validates_attachment_presence :image
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  validates_presence_of :name
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :certification
  has_many :meetings
end

app/models/subscriber.rb
require 'digest/sha2'

class Subscriber < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_uniqueness_of :email
  
  after_create :set_code
  
  def set_code
    self.code = Digest::SHA256.hexdigest("subscriber#{self.id}#{self.email}")
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments

  acts_as_authentic

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end  

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  filter_resource_access
  
  # GET /newsletters
  # GET /newsletters.xml
  def index
    @newsletters = Newsletter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @newsletters }
    end
  end

  # GET /newsletters/1
  # GET /newsletters/1.xml
  def show
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @newsletter }
    end
  end
  
  def view
    @newsletter = Newsletter.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # POST /newsletters
  # POST /newsletters.xml
  def create
    @newsletter = Newsletter.new(params[:newsletter])

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to(@newsletter, :notice => 'Newsletter was successfully created.') }
        format.xml  { render :xml => @newsletter, :status => :created, :location => @newsletter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @newsletter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.xml
  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to(newsletters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/newsletters/index.html.erb
<h1>Newsletters</h1>

<table>
  <tr>
		<th>Created</th>
    <th>Sent on</th>
		<% if permitted_to? :show %>
    	<th></th>
    	<th></th>
		<% end %>
  </tr>

<% @newsletters.each do |newsletter| %>
  <tr>
		<td><%= link_to newsletter.created_at.strftime( '%B %Y' ), view_newsletter_path( newsletter ) %></td>
    <td>
			<% unless newsletter.sent_on == nil %>
				<%= newsletter.sent_on %>
			<% else %>
				never
			<% end %>
		</td>
		<% if permitted_to? :show %>
    	<td><%= link_to 'Edit', newsletter %></td>
    	<td><%= link_to 'Destroy', newsletter, :confirm => 'Are you sure?', :method => :delete %></td>
		<% end %>
  </tr>
<% end %>
</table>

<% if permitted_to? :create %>
	<% content_for :pos2 do %>
		<div class="admin">
			<h1>Admin</h1>
			<%= link_to 'New Newsletter', newsletters_path, :method => :post %>
		</div>
	<% end %>
<% end %>

app/views/newsletters/show.html.erb
<h1><%= @newsletter.created_at.strftime( '%B %Y' ) %> Newsletter</h1>

<p>
  <b>Sent on:</b>
	<% unless @newsletter.sent_on == nil %>
  	<%= @newsletter.sent_on %>
	<% else %>
		never sent
	<% end %>
</p>

<article>
	<% @newsletter.newsletter_sections.each do |section| %>
		<section>
			<header><h2><%= section.title %></h2></header>
			<p>
				<% unless section.image_file_name.blank? %>
					<%= image_tag( section.image.url(:default), :class => 'image' ) %>
				<% end %>
			</p>
			<%= raw(textilize( section.content )) %>
			
			<p>
				<%= link_to 'Edit', edit_newsletter_newsletter_section_path(@newsletter,section) %>
				<%= link_to 'Destroy', [@newsletter,section], :method => :delete, :confirm => 'Are you sure?' %>
			</p>
		</section>
	<% end %>
</article>

<% content_for :pos2 do %>
	<div class="admin">
		<h1>Admin</h1>
		<%= link_to 'New Section', new_newsletter_newsletter_section_path(@newsletter) %>
		<%= link_to 'Reorder Sections', reorder_newsletter_newsletter_sections_path(@newsletter) %>
		<%= link_to 'Back', newsletters_path %>
	</div>
<% end %>

app/views/newsletters/view.html.erb
This is the view of the newsletter