config/routes.rb
PAL::Application.routes.draw do
  resources :newsletters do
    member do
      get :view
    end
    
    resources :newsletter_sections do
      collection do
        get :reorder
        post :sort
      end
    end
  end

  resources :subscribers do
    member do
      get :verify
    end
  end
  
  resources :class_requests
  resources :contacts
  resources :roles

  get "home/index"
  get "home/template"

  match 'logout' => 'user_sessions#destroy'
  
  resources :user_sessions
  resources :users
  resources :locations
  resources :meetings
  resources :certification_levels
  

  resources :certifications do
    resources :sections
  end

  resources :albums do
    resources :photos
  end

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy

  validates_presence_of :title
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  has_many :class_requests
  has_many :sections
  belongs_to :certification_level

  # scope include(:sections).order(:start_date).first  

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :certification_level_id
end

app/models/class_request.rb
class ClassRequest < ActiveRecord::Base
  belongs_to :certification
  
  validates_presence_of :from
  validates_presence_of :time
  
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :to
  validates_presence_of :from
  validates_presence_of :subject
  validates_presence_of :body
  
  validates_format_of :to, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :meetings

  validates_presence_of :name, :lat, :lng
  validates_numericality_of :lat, :lng
  validates_uniqueness_of :name
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :section
  belongs_to :location

  validates_presence_of :time
  validates_presence_of :section_id
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :newsletter_sections, :order => :position
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image #, :styles => {:display => "800x600>", :thumb => "100x100>", :tiny => "30x30>"}

  validates_presence_of :title
  validates_attachment_presence :image
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  validates_presence_of :name
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :certification
  has_many :meetings
end

app/models/subscriber.rb
require 'digest/sha2'

class Subscriber < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_uniqueness_of :email
  
  after_create :set_code
  
  def set_code
    self.code = Digest::SHA256.hexdigest("subscriber#{self.id}#{self.email}")
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments

  acts_as_authentic

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end  

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_certifications.html.erb
<div class="certifications">
	<h1>Certifications</h1>
	<ul>
		<li><%= link_to 'Beginning' %></li>
		<li><%= link_to 'Intermediate' %></li>
		<li><%= link_to 'Advanced' %></li>
		<li><%= link_to 'Professonal' %></li>
	</ul>
</div>

app/views/shared/_contact_us.html.erb
<div class="contact_us">
	<%= render :partial => 'shared/hcard' %>
</div>

app/views/shared/_flash_message.html.erb
<% if notice %>
    <p id="notice" class="flash"><%= notice %></p>
<% end  %>

<% if alert %>
    <p id="alert" class="flash"><%= alert %></p>
<% end  %>

app/views/shared/_footer.html.erb
<div class="narrow">
	<footer>
		<h1>Current Classes</h1>
		<ul>
			<li><%= link_to 'Open Water' %></li>
			<li><%= link_to 'Advanced Open Water' %></li>
			<li><%= link_to 'Navigation' %></li>
			<li><%= link_to 'Search and Recovery' %></li>
		</ul>
	
		<h1>All Courses</h1>
		<ul>
			<li><%= link_to 'Open Water' %></li>
			<li><%= link_to 'Advanced Open Water' %></li>
			<li><%= link_to 'Navigation' %></li>
			<li><%= link_to 'Search and Recovery' %></li>
			<li><%= link_to 'Dive Master' %></li>
			<li><%= link_to 'Master Diver' %></li>
			<li><%= link_to 'TEC Deep' %></li>
		</ul>
	
		<h1>Other Stuff</h1>
		<ul>
			<li><%= link_to 'Contact us', new_contact_path %></li>
			<li><%= link_to 'Facebook' %></li>
			<li><%= link_to 'Twitter' %></li>
		</ul>
	
		<section id="copyright">
			<%= image_tag 'small_logo.png' %>
			<p>
				Copyright &copy; <%= Time.now.year %> <%= link_to 'Poseidon Adventures Ltd.', new_user_session_path %>
				<% if current_user %>
					<%= link_to 'Logout', logout_path, :method => :delete %>
        <% end %>
			</p>
		</section>
	</footer>
</div>

app/views/shared/_hcard.html.erb
<article itemscope itemtype="http://data-vocabulary.org/Organization">
	<p class="links">
		<%= link_to 'Contact us' %>
		<%= link_to 'Who we are' %>
	</p>
	
	<h1 itemprop="name">Poseidon Adventures, Ltd.</h1>
	<p itemprop="address" itemscope itemtype="http://data-vocabulary.org/Address">
		<span itemprop="street-address">1234 S. Peoria Ave</span>
    <span itemprop="locality">Tulsa</span>,
    <span itemprop="region">OK</span>
    <span itemprop="postal-code">74555</span>
    <span itemprop="country-name">USA</span>
	</p>
	<p itemprop="tel">(918) 555-5555</p>
	<a itemprop="url" href="http://www.scubatulsa.com/">Poseidon Adventures Ltd.</a>
	<span itemprop="geo" itemscope itemtype="http://data-vocabulary.org/Geo">
    <meta itemprop="latitude" content="36.105686" />
    <meta itemprop="longitude" content="-95.976013" />
  </span>
</article>

app/views/shared/_header.html.erb
<div id="logo"><%= link_to( image_tag( 'logo.png' ), root_path ) %></div>
<h1>Poseidon Adventures Ltd.</h1>
<div id="bouy">
	<%= image_tag 'bouy.png' %>
</div>

<div id="header_forms">
	<%= form_for(Subscriber.new) do |f| %>
	    <%= f.text_field :email %>
	<% end %>
	
	<form action="" method="post">
		<input type="text" name="search" id="search" value="Search"/>
	</form>
</div>

app/views/shared/_media.html.erb
<% photo = Photo.first(:conditions => [ "id >= ?", rand(Photo.count)]) %>

<div class="media">
	<h1>Media</h1>
	<% if photo %>
		<p><%= image_tag photo.image.url, :width => 90 %></p>
		<h2><%= photo.title %></h2>
		<p class="description"><%= photo.description %></p>
	<% end %>
	<p><%= link_to 'Photo Albums', albums_path %></p>
</div>

app/views/shared/_scuba_nav.html.erb
<div class="scuba_nav">
	<h1>Scuba</h1>
	<ul>
		<li class="header">Education</li>
		<li><%= link_to 'Current Classes' %></li>
		<li><%= link_to 'Certifications', certifications_path %></li>
	</ul>

	<ul>
		<li class="header">Information</li>
		<li><%= link_to 'Articles' %></li>
		<li><%= link_to 'Resources and Links' %></li>
		<li><%= link_to 'Newsletters', newsletters_path %></li>
	</ul>

	<ul>
		<li class="header">Services</li>
		<li><%= link_to 'Equipment and Service' %></li>
		<li><%= link_to 'Travel and Vacations' %></li>
	</ul>

	<%= image_tag 'divers.png' %>
</div>

app/views/shared/_search_subscribe.html.erb
<div class="search_subscribe">
	<form action="" method="post">
		<input type="text" name="search_subscribe" id="search_subscribe_field" value="search or subscribe"/>
		<input type="submit" value="go"/>
	</form>
</div>

app/views/shared/_who_we_are.html.erb
<div class="who_we_are">
	<h1>Who we are</h1>
	<%= image_tag 'ben.png' %>
	<h2>Ben Brown</h2>
	<p>Master Scuba Instructor</p>
</div>