config/routes.rb
PAL::Application.routes.draw do
  resources :newsletters do
    member do
      get :view
    end
    
    resources :newsletter_sections do
      collection do
        get :reorder
        post :sort
      end
    end
  end

  resources :subscribers do
    member do
      get :verify
    end
  end
  
  resources :class_requests
  resources :contacts
  resources :roles

  get "home/index"
  get "home/template"

  match 'logout' => 'user_sessions#destroy'
  
  resources :user_sessions
  resources :users
  resources :locations
  resources :meetings
  resources :certification_levels
  

  resources :certifications do
    resources :sections
  end

  resources :albums do
    resources :photos
  end

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy

  validates_presence_of :title
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  has_many :class_requests
  has_many :sections
  belongs_to :certification_level

  # scope include(:sections).order(:start_date).first  

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :description
  validates_presence_of :certification_level_id
end

app/models/class_request.rb
class ClassRequest < ActiveRecord::Base
  belongs_to :certification
  
  validates_presence_of :from
  validates_presence_of :time
  
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :to
  validates_presence_of :from
  validates_presence_of :subject
  validates_presence_of :body
  
  validates_format_of :to, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_format_of :from, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :meetings

  validates_presence_of :name, :lat, :lng
  validates_numericality_of :lat, :lng
  validates_uniqueness_of :name
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :section
  belongs_to :location

  validates_presence_of :time
  validates_presence_of :section_id
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :newsletter_sections, :order => :position
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album

  has_attached_file :image #, :styles => {:display => "800x600>", :thumb => "100x100>", :tiny => "30x30>"}

  validates_presence_of :title
  validates_attachment_presence :image
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  validates_presence_of :name
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :certification
  has_many :meetings
end

app/models/subscriber.rb
require 'digest/sha2'

class Subscriber < ActiveRecord::Base
  validates_presence_of :email
  validates_format_of :email, :with => /^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3})|(aero|coop|info|museum|name))$/
  validates_uniqueness_of :email
  
  after_create :set_code
  
  def set_code
    self.code = Digest::SHA256.hexdigest("subscriber#{self.id}#{self.email}")
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments

  acts_as_authentic

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
end  

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  filter_resource_access

  # GET /certifications
  # GET /certifications.xml
  def index
    @certifications = Certification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @certifications }
    end
  end

  # GET /certifications/new
  # GET /certifications/new.xml
  def new
    @certification = Certification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @certification }
    end
  end

  # GET /certifications/1/edit
  def edit
    @certification = Certification.find(params[:id])
  end

  # POST /certifications
  # POST /certifications.xml
  def create
    @certification = Certification.new(params[:certification])

    respond_to do |format|
      if @certification.save
        format.html { redirect_to(certification_sections_url(@certification), :notice => 'Certification was successfully created.') }
        format.xml  { render :xml => @certification, :status => :created, :location => @certification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @certification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /certifications/1
  # PUT /certifications/1.xml
  def update
    @certification = Certification.find(params[:id])

    respond_to do |format|
      if @certification.update_attributes(params[:certification])
        format.html { redirect_to(certification_sections_url(@certification), :notice => 'Certification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @certification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.xml
  def destroy
    @certification = Certification.find(params[:id])
    @certification.destroy

    respond_to do |format|
      format.html { redirect_to(certifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/certifications/_form.html.erb
<%= form_for(@certification) do |f| %>
  <% if @certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% @certification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :certification_level %><br />
    <%= f.select :certification_level_id, CertificationLevel.all.map {|cl| [cl.name, cl.id]} %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<h1>Editing certification</h1>

<%= render 'form' %>

<% content_for :pos2 do %>
	<div class="admin">
		<h1>Admin</h1>
		<%= link_to 'Back', certifications_path %><br/>
		<%= link_to 'Show', certification_sections_path(@certification) %>
	</div>
<% end %>

app/views/certifications/index.html.erb
<h1>Certifications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @certifications.each do |certification| %>
  <tr>
    <td><%= link_to certification.name, certification_sections_path(certification) %></td>
    <td><%= truncate certification.description %></td>
    <% if permitted_to? :edit, certification %>
        <td><%= link_to 'Edit', edit_certification_path(certification) %></td>
    <% end %>
    <% if permitted_to? :destroy, certification %>
        <td><%= link_to 'Destroy', certification, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% content_for :pos2 do %>
	<div class="admin">
		<h1>Admin</h1>
		<%= link_to 'New Certification', new_certification_path %>
	</div>
<% end %>

app/views/certifications/new.html.erb
<h1>New Certification</h1>

<%= render 'form' %>


<% content_for :pos2 do %>
	<div class="admin">
		<h1>Admin</h1>
		<%= link_to 'Back', certifications_path %>
	</div>
<% end %>